# fly.toml app configuration file generated for a-hr on 2023-07-27T22:33:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "a-hr"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
